spring:
  application:
    name: Spring-data-Jpa-Homework
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
